# Generated by Django 4.1.7 on 2023-07-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0006_auto_20210528_2315'),
    ]

    operations = [
        migrations.CreateModel(
            name='feed',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('ptitle', models.CharField(max_length=255)),
                ('pcontent', models.TextField()),
                ('pimage', models.FileField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
