# Generated by Django 4.1.7 on 2023-07-23 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0007_feed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='pimage',
            field=models.FileField(upload_to='post/'),
        ),
    ]
